# Generated by Django 4.2.5 on 2025-04-10 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('focus_area', models.CharField(max_length=255)),
                ('est_value_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('est_value_max', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('is_accredited', models.BooleanField(default=False)),
                ('crypto_wallet', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_invested', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('plaid', 'Plaid Bank Transfer'), ('crypto', 'Crypto Wallet')], max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.investorprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.project')),
            ],
        ),
    ]
