# Generated by Django 4.2.5 on 2025-04-10 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='date_invested',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='crypto_wallet',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='is_accredited',
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='investment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('plaid', 'Plaid'), ('crypto', 'Crypto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='investment',
            name='project',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddField(
            model_name='payment',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.investment'),
        ),
    ]
