# Generated by Django 4.2.5 on 2025-04-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_payment_rename_date_invested_investment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('whitepaper_url', models.URLField(blank=True, null=True)),
                ('pitch_deck_url', models.URLField(blank=True, null=True)),
                ('funding_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('funding_max', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
