# Generated by Django 4.2.5 on 2025-04-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_payment_plaid_payment_id_project_funding_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='project',
            field=models.CharField(max_length=255),
        ),
    ]
