# Generated by Django 4.2.5 on 2025-04-15 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_alter_investment_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investments.project'),
        ),
    ]
