# Generated by Django 4.2.5 on 2025-05-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='agreement_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investment',
            name='agreement_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
