# Generated by Django 4.2.5 on 2025-05-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_investment_agreement_signed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pitch_deck_template',
            field=models.CharField(blank=True, help_text="Enter the path to the pitch deck template, e.g., 'pitchdecks/safex_pitch_deck.html'", max_length=255, null=True),
        ),
    ]
