from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('stripe/checkout/<int:investment_id>/', views.stripe_checkout, name='stripe_checkout'),
    path('payments/success/', views.payment_success, name='payment_success'),
    path('payments/cancel/', views.payment_cancel, name='payment_cancel'),
    path('onboarding/', views.onboarding, name='onboarding'),
    path('plaid/link-token/', views.create_link_token, name='create_link_token'),
    path('plaid/set-access-token/', views.set_access_token, name='set_access_token'),
    path('pay/', views.create_coinbase_charge, name='coinbase_charge'),
    path('webhook/', views.coinbase_webhook, name='coinbase_webhook'),
    #path('dag/whitepaper/', views.dag_whitepaper, name='dag_whitepaper'),
    path('dag/pitch-deck/', views.dag_pitch_deck, name='dag_pitch_deck'),
    #path('safex/whitepaper/', views.segurasafeswap_whitepaper, name='safex_whitepaper'),
    path('safex/pitch-deck/', views.segurasafeswap_pitch_deck, name='safex_pitch_deck'),
    #path('nexora/whitepaper/', views.cajunsea_whitepaper, name='nexora_whitepaper'),
    path('nexora/pitch-deck/', views.cajunsea_pitch_deck, name='nexora_pitch_deck'),
    #path('quadcopter/whitepaper/', views.mdav_whitepaper, name='quadcopter_whitepaper'),
    path('quadcopter/pitch-deck/', views.mdav_pitch_deck, name='quadcopter_pitch_deck'),
    #path('govtech/whitepaper/', views.govtech_whitepaper, name='govtech_whitepaper'),
    path('govtech/pitch-deck/', views.govtech_pitch_deck, name='govtech_pitch_deck'),
    #path('automatedtrading/whitepaper/', views.hftbot_whitepaper, name='automatedtrading_whitepaper'),
    path('automatedtrading/pitch-deck/', views.hftbot_pitch_deck, name='automatedtrading_pitch_deck'),
    #path('aichat/whitepaper/', views.aichat_whitepaper, name='aichat_whitepaper'),
    path('aichat/pitch-deck/', views.aichat_pitch_deck, name='aichat_pitch_deck'),
    #path('xactimate/whitepaper/', views.xactimate_whitepaper, name='xactimate_whitepaper'),
    path('xactimate/pitch-deck/', views.xactimate_pitch_deck, name='xactimate_pitch_deck'),
    #path('sam/whitepaper/', views.sam_whitepaper, name='sam_whitepaper'),
    path('sam/pitch-deck/', views.sam_pitch_deck, name='sam_pitch_deck'),
    #path('verisure/whitepaper/', views.segurainsures_whitepaper, name='verisure_whitepaper'),
    path('verisure/pitch-deck/', views.segurainsures_pitch_deck, name='verisure_pitch_deck'),
    #path('finovia/whitepaper/', views.segurafinance_whitepaper, name='finovia_whitepaper'),
    path('sgmt/pitch-deck/', views.sgmt_pitch_deck, name='sgmt_pitch_deck'),
    path('finovia/pitch-deck/', views.segurafinance_pitch_deck, name='finovia_pitch_deck'),
    path('civos/pitch-deck/', views.civos_pitch_deck, name='civos_pitch_deck'),
    path('investments/civos/pitch-deck/', views.civos_pitch_deck),
    path('investments/dag/pitch-deck/', views.dag_pitch_deck),
    path('investments/safex/pitch-deck/', views.segurasafeswap_pitch_deck),
    path('investments/nexora/pitch-deck/', views.cajunsea_pitch_deck),
    path('investments/quadcopter/pitch-deck/', views.mdav_pitch_deck),
    path('investments/govtech/pitch-deck/', views.govtech_pitch_deck),
    path('investments/automatedtrading/pitch-deck/', views.hftbot_pitch_deck),
    path('investments/aichat/pitch-deck/', views.aichat_pitch_deck),
    path('investments/xactimate/pitch-deck/', views.xactimate_pitch_deck),
    path('investments/sam/pitch-deck/', views.sam_pitch_deck),
    path('investments/verisure/pitch-deck/', views.segurainsures_pitch_deck),
    path('investments/sgmt/pitch-deck/', views.sgmt_pitch_deck),
    path('investments/finovia/pitch-deck/', views.segurafinance_pitch_deck),
    path('project/<int:project_id>/', views.project_detail, name='project_detail'),
    path('toggle-favorite/<int:project_id>/', views.toggle_favorite, name='toggle_favorite'),
    path('create-investment/', views.create_investment_then_stripe, name='create_investment'),
    path('funding-progress/<int:project_id>/', views.get_funding_progress, name='funding_progress'),
]
