from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('stripe/checkout/<int:investment_id>/', views.stripe_checkout, name='stripe_checkout'),
    path('payments/success/', views.payment_success, name='payment_success'),
    path('payments/cancel/', views.payment_cancel, name='payment_cancel'),
    path('onboarding/', views.onboarding, name='onboarding'),
    path('plaid/link-token/', views.create_link_token, name='create_link_token'),
    path('plaid/set-access-token/', views.set_access_token, name='set_access_token'),
    path('pay/', views.create_coinbase_charge, name='coinbase_charge'),
    path('webhook/', views.coinbase_webhook, name='coinbase_webhook'),
    path('dag/whitepaper/', views.dag_whitepaper, name='dag_whitepaper'),
    path('dag/pitch-deck/', views.dag_pitch_deck, name='pitch_deck'),
    path('segurasafeswap/whitepaper/', views.segurasafeswap_whitepaper, name='segurasafeswap_whitepaper'),
    path('segurasafeswap/pitch-deck/', views.segurasafeswap_pitch_deck, name='segurasafeswap_pitch_deck'),
    path('cajunsea/whitepaper/', views.cajunsea_whitepaper, name='cajunsea_whitepaper'),
    path('cajunsea/pitch-deck/', views.cajunsea_pitch_deck, name='cajunsea_pitch_deck'),
    path('mdav/whitepaper/', views.mdav_whitepaper, name='mdav_whitepaper'),
    path('mdav/pitch-deck/', views.mdav_pitch_deck, name='mdav_pitch_deck'),
    path('govtech/whitepaper/', views.govtech_whitepaper, name='govtech_whitepaper'),
    path('govtech/pitch-deck/', views.govtech_pitch_deck, name='govtech_pitch_deck'),
    path('hftbot/whitepaper/', views.hftbot_whitepaper, name='hftbot_whitepaper'),
    path('hftbot/pitch-deck/', views.hftbot_pitch_deck, name='hftbot_pitch_deck'),
    path('aichat/whitepaper/', views.aichat_whitepaper, name='aichat_whitepaper'),
    path('aichat/pitch-deck/', views.aichat_pitch_deck, name='aichat_pitch_deck'),
    path('arparks/whitepaper/', views.arparks_whitepaper, name='arparks_whitepaper'),
    path('arparks/pitch-deck/', views.arparks_pitch_deck, name='arparks_pitch_deck'),
    path('nga/whitepaper/', views.nga_whitepaper, name='nga_whitepaper'),
    path('nga/pitch-deck/', views.nga_pitch_deck, name='nga_pitch_deck'),
    path('xactimate/whitepaper/', views.xactimate_whitepaper, name='xactimate_whitepaper'),
    path('xactimate/pitch-deck/', views.xactimate_pitch_deck, name='xactimate_pitch_deck'),
    path('sam/whitepaper/', views.sam_whitepaper, name='sam_whitepaper'),
    path('sam/pitch-deck/', views.sam_pitch_deck, name='sam_pitch_deck'),
    path('segurainsures/whitepaper/', views.segurainsures_whitepaper, name='segurainsures_whitepaper'),
    path('segurainsures/pitch-deck/', views.segurainsures_pitch_deck, name='segurainsures_pitch_deck'),
    path('segurafinance/whitepaper/', views.segurafinance_whitepaper, name='segurafinance_whitepaper'),
    path('segurafinance/pitch-deck/', views.segurafinance_pitch_deck, name='segurafinance_pitch_deck'),
    path('project/<int:project_id>/', views.project_detail, name='project_detail'),
    path('toggle-favorite/<int:project_id>/', views.toggle_favorite, name='toggle_favorite'),
]
