# Generated by Django 4.2.5 on 2025-05-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investoroutreach', '0002_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='clicked',
            field=models.BooleanField(default=False),
        ),
    ]
