# Generated by Django 4.2.5 on 2025-05-15 18:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scopegen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopeofwork',
            name='category',
            field=models.CharField(choices=[('AI', 'AI/ML'), ('BC', 'Blockchain'), ('WD', 'Web Development'), ('FT', 'Fintech'), ('DV', 'Defense / GovTech'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='scopeofwork',
            name='is_approved_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scopeofwork',
            name='is_shared',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scopeofwork',
            name='share_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
