# Generated by Django 4.2.5 on 2025-05-16 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scopegen', '0002_scopeofwork_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='scopeofwork',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='scopeofwork',
            old_name='is_approved_by_admin',
            new_name='is_approved',
        ),
        migrations.AddField(
            model_name='scopeofwork',
            name='is_pitch_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='category',
            field=models.CharField(choices=[('ai', 'AI/ML'), ('blockchain', 'Blockchain'), ('web', 'Web Dev'), ('mobile', 'Mobile App'), ('data', 'Data Science'), ('general', 'General')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='generated_scope',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='share_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='timeline',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='tools',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scopeofwork',
            name='tags',
            field=models.ManyToManyField(blank=True, to='scopegen.scopetag'),
        ),
    ]
