# Generated by Django 4.2.5 on 2025-05-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopegen', '0003_scopetag_alter_scopeofwork_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopeofwork',
            name='is_hiring',
            field=models.BooleanField(default=False),
        ),
    ]
